on: [push, pull_request]
name: Test
jobs:
  test:
    env:
      # The special value "local" tells Go to use the bundled Go
      # version rather than trying to fetch one according to a
      # `toolchain` value in `go.mod`. This ensures that we're
      # really running the Go version in the CI matrix rather than
      # one that the Go command has upgraded to automatically.
      #
      # See https://brandur.org/fragments/go-version-matrix
      GOTOOLCHAIN: local
    strategy:
      matrix:
        go-version: ['1.18', '1.19', '1.20', '1.21', '1.22', '1.23']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    - run: go test -race -v ./...
