on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: ['1.18', '1.19', '1.20', '1.21', '1.22.0-rc.1']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    - run: go test ./...
    - run: go test -race ./...
